--- 
settings_001: 
  created_at: 2011-06-10 12:09:04
  id: "1"
  updated_at: 2011-06-10 12:09:04
  value: |
    --- admin@admin.admin

  var: admin_email
settings_002: 
  created_at: 2011-06-10 12:09:04
  id: "2"
  updated_at: 2011-06-10 12:09:04
  value: |
    --- School of Art Digital Technology Office

  var: department_name
settings_003: 
  created_at: 2011-06-10 12:09:04
  id: "3"
  updated_at: 2011-06-10 12:09:04
  value: |
    --- |-
    Dear @user@,
      Please remember to come pick up the following equipment that you reserved:
    
      @equipment_list@
    
      If you do not intend to check these items out, you must cancel your reservation at least 24 hours before it is due for check out. If you frequently miss your reservations then the privilege to make further reservations for the rest of the term will be revoked.
    
      Thank you,
      @department_name@

  var: upcoming_checkout_email_body
settings_004: 
  created_at: 2011-06-10 12:09:04
  id: "4"
  updated_at: 2011-06-10 12:09:04
  value: |
    --- |-
    Dear @user@,
      Please remember to return the equipment you borrowed from us:
    
      @equipment_list@
    
      If the equipment is returned after 4 pm on @return_date@ you will be charged a late fee or replacement fee. Repeated late returns will result in the privilege to make further reservations for the rest of the term to be revoked.
    
      Thank you,
      @department_name@

  var: upcoming_checkin_email_body
settings_005: 
  created_at: 2011-06-10 12:09:04
  id: "5"
  updated_at: 2011-06-10 12:09:04
  value: |
    --- |-
    Dear @user@,
      You have missed a scheduled equipment checkout, so your equipment may be released and checked out to other students.
    
      Thank you,
      @department_name@

  var: overdue_checkout_email_body
settings_006: 
  created_at: 2011-06-10 12:09:04
  id: "6"
  updated_at: 2011-06-10 12:09:04
  value: |
    --- |-
    Dear @user@,
      You were supposed to return the equipment you borrowed from us on @return_date@ but because you have failed to do so, you will be charged @late_fee@ / day until the equipment is returned. Failure to return equipment will result in replacement fees and revocation of borrowing privileges.
    
      Thank you,
      @department_name@

  var: overdue_checkin_email_body
