# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults

development:
  <<: *defaults
  secret_key_base: 0c114ce3c8f99376a19fe18c87a9a83bba6364236850234b2e674640b23c3be5ac8658f339910de5dd138ba4456f30f6efdb69ab8c09eafbe2cd04845ff92fac

test:
  <<: *defaults
  secret_key_base: 9120aa3282dfe21ba166d77e0a389ef1d47a5b0a81852f7d17a3f985ad51cd96b3a2d9294237780f7ffce8d88fac6bc467c2768afa86f55baa997536a0b3d97e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>